env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "react/jsx-uses-react": "off",
  "react/react-in-jsx-scope": "off",
  "react/jsx-filename-extension": "off",
  "react/jsx-props-no-spreading": "off",
  "react/forbid-prop-types": "off",
  "consistent-return": "off",
  "no-param-reassign": "off",
  "max-len": [ "error", { "code": 120 } ]
}
